### ISSUE TITLE
Sort-Arrows not working if DataGridStateProvider is Used

### ISSUE THREAD

**Issue by mvitzthum** [DCCS-IT-Business-Solutions/react-table-plain#8]
Change:
![image](https://user-images.githubusercontent.com/47003029/60015389-aa169680-9683-11e9-94b8-64ad0969ba5e.png)

to:

![image](https://user-images.githubusercontent.com/47003029/60015400-b569c200-9683-11e9-9377-3d813049fbf8.png)

**Comment by stephanmeissner** [comment]
PR merged. Done.
